// The .source alias will be generated by 'fumadocs-mdx' postinstall script
// or when you run `next dev`.
// If TypeScript complains about '@/.source', you might need to run `npm run postinstall`
// or `npm run dev` once to generate it.
import { docs } from '../.source/index';
import { loader } from 'fumadocs-core/source';
import { icons } from 'lucide-react';
import { createElement } from 'react';
import { DeployStackLogo } from './components/DeployStackLogo';

export const source = loader({
  // Base URL for the documentation pages.
  // Since we've moved docs to the root level, baseUrl should be '/'
  // This means docs/index.mdx will be at / and other docs at their direct paths
  baseUrl: '/',
  // The source of the documents, converted to Fumadocs format.
  source: docs.toFumadocsSource(),
  
  
  // Icon handler to support both lucide-react icons and custom icons
  icon(icon) {
    if (!icon) {
      return; // No icon specified
    }
    
    // Handle custom icons
    if (icon === 'DeployStackLogo') {
      return createElement(DeployStackLogo);
    }
    
    // Handle lucide-react icons
    if (icon in icons) {
      return createElement(icons[icon as keyof typeof icons]);
    }
    
    // If icon not found, return undefined
    return undefined;
  },

  // Customize page tree to support custom sidebar titles
  pageTree: {
    attachFile(node, file) {
      // If the file has a custom sidebar title, use it instead of the title
      if (file?.data && 'sidebar' in file.data && file.data.sidebar) {
        node.name = file.data.sidebar as string;
      }
      return node;
    },
  },

  // Optional: You can define global MDX components here if not done elsewhere
  // globalMdxComponents: getMDXComponents(),
});

// You might also want to export page tree and other utilities if needed directly
// export const pageTree = source.pageTree;
// export const getPage = source.getPage;
// export const generateParams = source.generateParams;
